#!/usr/bin/env zsh
emulate -L zsh

local label
local -i n r s=SECONDS
local -a ret
for label n (
	d 86400
	h 3600
	m 60
){
	if (((r = s / n) || $#ret)); then
		ret+=($r$label)
	fi
	((s %= n))
}
ret+=("$s"s)

reply+=('Shell Uptime' ${(j: :)ret})
