#!/usr/bin/env zsh
emulate -L zsh

autoload add-zle-hook-widget
functions[.shellfetch-zle-keymap-select]='_sf_last_keymap=$KEYMAP;'
add-zle-hook-widget zle-keymap-select .shellfetch-zle-keymap-select
